# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookshop.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 574)
        MainWindow.setMinimumSize(QtCore.QSize(850, 500))
        MainWindow.setWindowOpacity(1.0)
        self.styleWidget = QtWidgets.QWidget(MainWindow)
        self.styleWidget.setStyleSheet("/**************************************************************/\n"
"/*                                                        MAIN WINDOW                                             */\n"
"\n"
"* {\n"
"background-color: #363432;\n"
"color: #F0941F;\n"
"}\n"
"\n"
"/**************************************************************/\n"
"/*                                                        COMMAND LINK BUTTON                             */\n"
"QCommandLinkButton {\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    color: #EF6024;\n"
"\n"
"}\n"
"QCommandLinkButton:hover {\n"
"    color: #90A19D;\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"    color: #90A19D;\n"
"    background-color: rgb(52, 58, 71);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/**************************************************************/\n"
"/*                                                        LINE EDITS                                                         */\n"
"\n"
"#signupPage QLineEdit, #loginPage QLineEdit {\n"
"    border: 1px solid #90A19D;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font: 15pt \"MS Sans Serif\";\n"
"}\n"
"#signupPage QLineEdit:hover, #loginPage QLineEdit {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"#signupPage QLineEdit:focus, #loginPage QLineEdit {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/**************************************************************/\n"
"/*                                                        PUSH BUTTONS                                                         */\n"
"\n"
"QPushButton {\n"
"font: 10pt \"MV Boli\";\n"
"padding: 10px 40px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"QPushButton::pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"/**************************************************************/\n"
"/*                                                        TABLE WIDGET                                             */\n"
"QTableWidget {\n"
"background: white;\n"
"}\n"
"QHeaderView::section {\n"
"border-style: none;\n"
"color: white;\n"
"background-color: #EF6024;\n"
"border-radius:14px;\n"
"}\n"
"QTableView::item {\n"
"border: 1px solid #363432;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/**************************************************************/\n"
"/*                                                        SCROLL BAR                                                 */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background:#EF6024;\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: #EF6024;\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/**************************************************************/\n"
"/*                                                        OTHERS                                                         */\n"
"\n"
"#right_frame QLabel, #right_frame_2 QLabel {\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"#right_frame #signup_link_message, #right_frame_2  #login_link_message {\n"
"color: #90A19D;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"\n"
"#leftMenuBg {    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"#titleLeftApp { font: 63 12pt \"Segoe UI Semibold\"; }\n"
"#titleLeftDescription { font: 8pt \"Segoe UI\"; color: rgb(189, 147, 249); }\n"
"\n"
"\n"
"/* MENUS */\n"
"#topMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 16px solid transparent;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#topMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#topMenu .QPushButton:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#bottomMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#bottomMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#bottomMenu .QPushButton:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#leftMenuFrame{\n"
"    border-top: 3px solid rgb(44, 49, 58);\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color: rgb(37, 41, 48);\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: rgb(113, 126, 149);\n"
"}\n"
"#toggleButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#toggleButton:pressed {\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo { padding-left: 10px; }\n"
"\n"
"\n"
"\n"
"#adminLogoutBtn{\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#adminLogoutBtn::hover{\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#adminLogoutBtn::pressed{\n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.styleWidget.setObjectName("styleWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.styleWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.styleWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.loginPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_frame = QtWidgets.QFrame(self.loginPage)
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.left_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.welcome_message = QtWidgets.QLabel(self.left_frame)
        self.welcome_message.setObjectName("welcome_message")
        self.verticalLayout_3.addWidget(self.welcome_message)
        self.horizontalLayout_2.addWidget(self.left_frame)
        self.right_frame = QtWidgets.QFrame(self.loginPage)
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelUsername = QtWidgets.QLabel(self.right_frame)
        self.labelUsername.setObjectName("labelUsername")
        self.verticalLayout_2.addWidget(self.labelUsername)
        self.inputUsername = QtWidgets.QLineEdit(self.right_frame)
        self.inputUsername.setObjectName("inputUsername")
        self.verticalLayout_2.addWidget(self.inputUsername)
        self.username_message_label = QtWidgets.QLabel(self.right_frame)
        self.username_message_label.setStyleSheet("color: #EF6024;")
        self.username_message_label.setText("")
        self.username_message_label.setObjectName("username_message_label")
        self.verticalLayout_2.addWidget(self.username_message_label)
        self.labelPassword = QtWidgets.QLabel(self.right_frame)
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout_2.addWidget(self.labelPassword)
        self.inputPassword = QtWidgets.QLineEdit(self.right_frame)
        self.inputPassword.setText("")
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword.setObjectName("inputPassword")
        self.verticalLayout_2.addWidget(self.inputPassword)
        self.password_message_label = QtWidgets.QLabel(self.right_frame)
        self.password_message_label.setStyleSheet("color: #EF6024")
        self.password_message_label.setText("")
        self.password_message_label.setObjectName("password_message_label")
        self.verticalLayout_2.addWidget(self.password_message_label)
        self.loginBtn = QtWidgets.QPushButton(self.right_frame)
        self.loginBtn.setObjectName("loginBtn")
        self.verticalLayout_2.addWidget(self.loginBtn, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.right_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.signup_link_message = QtWidgets.QLabel(self.frame_3)
        self.signup_link_message.setObjectName("signup_link_message")
        self.horizontalLayout_5.addWidget(self.signup_link_message)
        self.signupCommandBtn = QtWidgets.QCommandLinkButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signupCommandBtn.sizePolicy().hasHeightForWidth())
        self.signupCommandBtn.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-user-follow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signupCommandBtn.setIcon(icon)
        self.signupCommandBtn.setObjectName("signupCommandBtn")
        self.horizontalLayout_5.addWidget(self.signupCommandBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.right_frame)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.stackedWidget.addWidget(self.loginPage)
        self.signupPage = QtWidgets.QWidget()
        self.signupPage.setObjectName("signupPage")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.signupPage)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_frame_2 = QtWidgets.QFrame(self.signupPage)
        self.left_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame_2.setObjectName("left_frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.left_frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.left_frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.welcome_message_2 = QtWidgets.QLabel(self.left_frame_2)
        self.welcome_message_2.setObjectName("welcome_message_2")
        self.verticalLayout_4.addWidget(self.welcome_message_2)
        self.horizontalLayout_3.addWidget(self.left_frame_2)
        self.right_frame_2 = QtWidgets.QFrame(self.signupPage)
        self.right_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame_2.setObjectName("right_frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.right_frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelUsername_2 = QtWidgets.QLabel(self.right_frame_2)
        self.labelUsername_2.setObjectName("labelUsername_2")
        self.verticalLayout_5.addWidget(self.labelUsername_2)
        self.inputUsername_signupPage = QtWidgets.QLineEdit(self.right_frame_2)
        self.inputUsername_signupPage.setObjectName("inputUsername_signupPage")
        self.verticalLayout_5.addWidget(self.inputUsername_signupPage)
        self.username_message_label_signupPage = QtWidgets.QLabel(self.right_frame_2)
        self.username_message_label_signupPage.setStyleSheet("color: #EF6024;")
        self.username_message_label_signupPage.setText("")
        self.username_message_label_signupPage.setObjectName("username_message_label_signupPage")
        self.verticalLayout_5.addWidget(self.username_message_label_signupPage)
        self.labelPassword_2 = QtWidgets.QLabel(self.right_frame_2)
        self.labelPassword_2.setObjectName("labelPassword_2")
        self.verticalLayout_5.addWidget(self.labelPassword_2)
        self.inputPassword_signupPage = QtWidgets.QLineEdit(self.right_frame_2)
        self.inputPassword_signupPage.setText("")
        self.inputPassword_signupPage.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword_signupPage.setObjectName("inputPassword_signupPage")
        self.verticalLayout_5.addWidget(self.inputPassword_signupPage)
        self.password_message_label_signupPage = QtWidgets.QLabel(self.right_frame_2)
        self.password_message_label_signupPage.setStyleSheet("color: #EF6024")
        self.password_message_label_signupPage.setText("")
        self.password_message_label_signupPage.setObjectName("password_message_label_signupPage")
        self.verticalLayout_5.addWidget(self.password_message_label_signupPage)
        self.label = QtWidgets.QLabel(self.right_frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.inputConfirmPassword = QtWidgets.QLineEdit(self.right_frame_2)
        self.inputConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputConfirmPassword.setObjectName("inputConfirmPassword")
        self.verticalLayout_5.addWidget(self.inputConfirmPassword)
        self.confirm_password_message_label_signupPage = QtWidgets.QLabel(self.right_frame_2)
        self.confirm_password_message_label_signupPage.setStyleSheet("color: #EF6024;")
        self.confirm_password_message_label_signupPage.setText("")
        self.confirm_password_message_label_signupPage.setObjectName("confirm_password_message_label_signupPage")
        self.verticalLayout_5.addWidget(self.confirm_password_message_label_signupPage)
        self.signupBtn = QtWidgets.QPushButton(self.right_frame_2)
        self.signupBtn.setObjectName("signupBtn")
        self.verticalLayout_5.addWidget(self.signupBtn, 0, QtCore.Qt.AlignHCenter)
        self.frame_2 = QtWidgets.QFrame(self.right_frame_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.login_link_message = QtWidgets.QLabel(self.frame_2)
        self.login_link_message.setObjectName("login_link_message")
        self.horizontalLayout_4.addWidget(self.login_link_message)
        self.loginCommandBtn = QtWidgets.QCommandLinkButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginCommandBtn.sizePolicy().hasHeightForWidth())
        self.loginCommandBtn.setSizePolicy(sizePolicy)
        self.loginCommandBtn.setIcon(icon)
        self.loginCommandBtn.setObjectName("loginCommandBtn")
        self.horizontalLayout_4.addWidget(self.loginCommandBtn, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.horizontalLayout_3.addWidget(self.right_frame_2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.stackedWidget.addWidget(self.signupPage)
        self.adminPage = QtWidgets.QWidget()
        self.adminPage.setObjectName("adminPage")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.adminPage)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.bgApp = QtWidgets.QFrame(self.adminPage)
        self.bgApp.setStyleSheet("")
        self.bgApp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bgApp.setObjectName("bgApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.leftMenuBg = QtWidgets.QFrame(self.bgApp)
        self.leftMenuBg.setMinimumSize(QtCore.QSize(60, 0))
        self.leftMenuBg.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftMenuBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuBg.setObjectName("leftMenuBg")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.leftMenuBg)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenuBg)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalMenuLayout = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalMenuLayout.setContentsMargins(0, 0, 0, 30)
        self.verticalMenuLayout.setSpacing(0)
        self.verticalMenuLayout.setObjectName("verticalMenuLayout")
        self.topMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.topMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenu.setObjectName("topMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_users = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_users.sizePolicy().hasHeightForWidth())
        self.btn_users.setSizePolicy(sizePolicy)
        self.btn_users.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_users.setFont(font)
        self.btn_users.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_users.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_users.setStyleSheet("background-image: url(:/icons/images/icons/cil-customer.png);\n"
"")
        self.btn_users.setObjectName("btn_users")
        self.verticalLayout_8.addWidget(self.btn_users)
        self.btn_books = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_books.sizePolicy().hasHeightForWidth())
        self.btn_books.setSizePolicy(sizePolicy)
        self.btn_books.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_books.setFont(font)
        self.btn_books.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_books.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_books.setStyleSheet("background-image: url(:/icons/images/icons/cil-product.png);\n"
"")
        self.btn_books.setObjectName("btn_books")
        self.verticalLayout_8.addWidget(self.btn_books)
        self.btn_orders = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_orders.sizePolicy().hasHeightForWidth())
        self.btn_orders.setSizePolicy(sizePolicy)
        self.btn_orders.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_orders.setFont(font)
        self.btn_orders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_orders.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_orders.setStyleSheet("background-image: url(:/icons/images/icons/cil-order.png);\n"
"")
        self.btn_orders.setObjectName("btn_orders")
        self.verticalLayout_8.addWidget(self.btn_orders)
        self.btn_orderItems = QtWidgets.QPushButton(self.topMenu)
        self.btn_orderItems.setStyleSheet("background-image: url(:/books/images/icons/icons8-boxes-32.png);\n"
"")
        self.btn_orderItems.setObjectName("btn_orderItems")
        self.verticalLayout_8.addWidget(self.btn_orderItems)
        self.verticalMenuLayout.addWidget(self.topMenu, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalMenuLayout.addItem(spacerItem)
        self.adminLogoutBtn = QtWidgets.QPushButton(self.leftMenuFrame)
        self.adminLogoutBtn.setStyleSheet("background-image: url(:/icons/images/icons/cil-account-logout.png);\n"
"")
        self.adminLogoutBtn.setText("")
        self.adminLogoutBtn.setObjectName("adminLogoutBtn")
        self.verticalMenuLayout.addWidget(self.adminLogoutBtn)
        self.verticalLayout_6.addWidget(self.leftMenuFrame)
        self.appLayout.addWidget(self.leftMenuBg)
        self.contentBox = QtWidgets.QFrame(self.bgApp)
        self.contentBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.contentBottom = QtWidgets.QFrame(self.contentBox)
        self.contentBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.content = QtWidgets.QFrame(self.contentBottom)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pagesContainer = QtWidgets.QFrame(self.content)
        self.pagesContainer.setStyleSheet("QTableWidget {\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"border: 1px solid white;\n"
"}\n"
"")
        self.pagesContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pagesContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pagesContainer.setObjectName("pagesContainer")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.pagesContainer)
        self.verticalLayout_16.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.adminStackedWidget = QtWidgets.QStackedWidget(self.pagesContainer)
        self.adminStackedWidget.setStyleSheet("background: transparent;\n"
"")
        self.adminStackedWidget.setObjectName("adminStackedWidget")
        self.users = QtWidgets.QWidget()
        self.users.setStyleSheet("")
        self.users.setObjectName("users")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.users)
        self.verticalLayout_17.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_17.setSpacing(10)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.user_frame = QtWidgets.QFrame(self.users)
        self.user_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_frame.setObjectName("user_frame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.user_frame)
        self.verticalLayout_18.setSpacing(10)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_4 = QtWidgets.QFrame(self.user_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_19.setSpacing(15)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.customer_label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.customer_label.setFont(font)
        self.customer_label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.customer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.customer_label.setObjectName("customer_label")
        self.verticalLayout_19.addWidget(self.customer_label, 0, QtCore.Qt.AlignTop)
        self.userTableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.userTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.userTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.userTableWidget.setObjectName("userTableWidget")
        self.userTableWidget.setColumnCount(4)
        self.userTableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.userTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_19.addWidget(self.userTableWidget)
        self.verticalLayout_18.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.user_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.user_add_button = QtWidgets.QPushButton(self.frame_5)
        self.user_add_button.setMinimumSize(QtCore.QSize(100, 40))
        self.user_add_button.setObjectName("user_add_button")
        self.horizontalLayout_10.addWidget(self.user_add_button)
        self.user_update_button = QtWidgets.QPushButton(self.frame_5)
        self.user_update_button.setMinimumSize(QtCore.QSize(100, 40))
        self.user_update_button.setObjectName("user_update_button")
        self.horizontalLayout_10.addWidget(self.user_update_button)
        self.user_delete_button = QtWidgets.QPushButton(self.frame_5)
        self.user_delete_button.setMinimumSize(QtCore.QSize(100, 40))
        self.user_delete_button.setObjectName("user_delete_button")
        self.horizontalLayout_10.addWidget(self.user_delete_button)
        self.verticalLayout_18.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_18.setStretch(0, 6)
        self.verticalLayout_18.setStretch(1, 1)
        self.verticalLayout_17.addWidget(self.user_frame)
        self.adminStackedWidget.addWidget(self.users)
        self.books = QtWidgets.QWidget()
        self.books.setObjectName("books")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.books)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_6 = QtWidgets.QFrame(self.books)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_23.setSpacing(15)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.product_label = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.product_label.setFont(font)
        self.product_label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.product_label.setAlignment(QtCore.Qt.AlignCenter)
        self.product_label.setObjectName("product_label")
        self.verticalLayout_23.addWidget(self.product_label)
        self.bookTableWidget = QtWidgets.QTableWidget(self.frame_7)
        self.bookTableWidget.setStyleSheet("")
        self.bookTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bookTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.bookTableWidget.setObjectName("bookTableWidget")
        self.bookTableWidget.setColumnCount(6)
        self.bookTableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTableWidget.setHorizontalHeaderItem(5, item)
        self.bookTableWidget.horizontalHeader().setStretchLastSection(False)
        self.bookTableWidget.verticalHeader().setHighlightSections(True)
        self.bookTableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_23.addWidget(self.bookTableWidget)
        self.verticalLayout_21.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.book_add_button = QtWidgets.QPushButton(self.frame_8)
        self.book_add_button.setMinimumSize(QtCore.QSize(100, 40))
        self.book_add_button.setObjectName("book_add_button")
        self.horizontalLayout_11.addWidget(self.book_add_button)
        self.book_update_button = QtWidgets.QPushButton(self.frame_8)
        self.book_update_button.setMinimumSize(QtCore.QSize(100, 40))
        self.book_update_button.setObjectName("book_update_button")
        self.horizontalLayout_11.addWidget(self.book_update_button)
        self.book_delete_button = QtWidgets.QPushButton(self.frame_8)
        self.book_delete_button.setMinimumSize(QtCore.QSize(100, 40))
        self.book_delete_button.setObjectName("book_delete_button")
        self.horizontalLayout_11.addWidget(self.book_delete_button)
        self.verticalLayout_21.addWidget(self.frame_8, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_21.setStretch(0, 6)
        self.verticalLayout_21.setStretch(1, 1)
        self.verticalLayout_22.addWidget(self.frame_6)
        self.adminStackedWidget.addWidget(self.books)
        self.orders = QtWidgets.QWidget()
        self.orders.setObjectName("orders")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.orders)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.order_frame = QtWidgets.QFrame(self.orders)
        self.order_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.order_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.order_frame.setObjectName("order_frame")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.order_frame)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_9 = QtWidgets.QFrame(self.order_frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_25.setSpacing(15)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.order_label = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.order_label.setFont(font)
        self.order_label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.order_label.setAlignment(QtCore.Qt.AlignCenter)
        self.order_label.setObjectName("order_label")
        self.verticalLayout_25.addWidget(self.order_label)
        self.orderTableWidget = QtWidgets.QTableWidget(self.frame_9)
        self.orderTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.orderTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.orderTableWidget.setObjectName("orderTableWidget")
        self.orderTableWidget.setColumnCount(4)
        self.orderTableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(3, item)
        self.orderTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.orderTableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.verticalLayout_25.addWidget(self.orderTableWidget)
        self.verticalLayout_24.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.order_frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.order_add_button = QtWidgets.QPushButton(self.frame_10)
        self.order_add_button.setMinimumSize(QtCore.QSize(100, 40))
        self.order_add_button.setObjectName("order_add_button")
        self.horizontalLayout_12.addWidget(self.order_add_button)
        self.order_update_button = QtWidgets.QPushButton(self.frame_10)
        self.order_update_button.setMinimumSize(QtCore.QSize(100, 40))
        self.order_update_button.setObjectName("order_update_button")
        self.horizontalLayout_12.addWidget(self.order_update_button)
        self.order_delete_button = QtWidgets.QPushButton(self.frame_10)
        self.order_delete_button.setMinimumSize(QtCore.QSize(100, 40))
        self.order_delete_button.setObjectName("order_delete_button")
        self.horizontalLayout_12.addWidget(self.order_delete_button)
        self.verticalLayout_24.addWidget(self.frame_10, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_24.setStretch(0, 6)
        self.verticalLayout_24.setStretch(1, 1)
        self.verticalLayout_20.addWidget(self.order_frame)
        self.adminStackedWidget.addWidget(self.orders)
        self.orderItems = QtWidgets.QWidget()
        self.orderItems.setObjectName("orderItems")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.orderItems)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.order_item_frame = QtWidgets.QFrame(self.orderItems)
        self.order_item_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.order_item_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.order_item_frame.setObjectName("order_item_frame")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.order_item_frame)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_11 = QtWidgets.QFrame(self.order_item_frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_27.setSpacing(15)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.order_item_label = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.order_item_label.setFont(font)
        self.order_item_label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.order_item_label.setAlignment(QtCore.Qt.AlignCenter)
        self.order_item_label.setObjectName("order_item_label")
        self.verticalLayout_27.addWidget(self.order_item_label)
        self.orderItemTableWidget = QtWidgets.QTableWidget(self.frame_11)
        self.orderItemTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.orderItemTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.orderItemTableWidget.setObjectName("orderItemTableWidget")
        self.orderItemTableWidget.setColumnCount(5)
        self.orderItemTableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.orderItemTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderItemTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderItemTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderItemTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderItemTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderItemTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderItemTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderItemTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderItemTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderItemTableWidget.setHorizontalHeaderItem(4, item)
        self.orderItemTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.orderItemTableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.verticalLayout_27.addWidget(self.orderItemTableWidget)
        self.verticalLayout_26.addWidget(self.frame_11)
        self.frame_15 = QtWidgets.QFrame(self.order_item_frame)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.order_item_add_button = QtWidgets.QPushButton(self.frame_15)
        self.order_item_add_button.setMinimumSize(QtCore.QSize(100, 40))
        self.order_item_add_button.setObjectName("order_item_add_button")
        self.horizontalLayout_15.addWidget(self.order_item_add_button)
        self.order_item_update_button = QtWidgets.QPushButton(self.frame_15)
        self.order_item_update_button.setMinimumSize(QtCore.QSize(100, 40))
        self.order_item_update_button.setObjectName("order_item_update_button")
        self.horizontalLayout_15.addWidget(self.order_item_update_button)
        self.order_item_delete_button = QtWidgets.QPushButton(self.frame_15)
        self.order_item_delete_button.setMinimumSize(QtCore.QSize(100, 40))
        self.order_item_delete_button.setObjectName("order_item_delete_button")
        self.horizontalLayout_15.addWidget(self.order_item_delete_button)
        self.verticalLayout_26.addWidget(self.frame_15, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_26.setStretch(0, 6)
        self.verticalLayout_26.setStretch(1, 1)
        self.verticalLayout_7.addWidget(self.order_item_frame)
        self.adminStackedWidget.addWidget(self.orderItems)
        self.verticalLayout_16.addWidget(self.adminStackedWidget)
        self.horizontalLayout_9.addWidget(self.pagesContainer)
        self.verticalLayout_15.addWidget(self.content)
        self.verticalLayout_14.addWidget(self.contentBottom)
        self.appLayout.addWidget(self.contentBox)
        self.verticalLayout_29.addWidget(self.bgApp)
        self.stackedWidget.addWidget(self.adminPage)
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.homePage)
        self.verticalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_48.setSpacing(0)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.contentBox_2 = QtWidgets.QFrame(self.homePage)
        self.contentBox_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBox_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox_2.setObjectName("contentBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.contentBox_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.contentBottom_2 = QtWidgets.QFrame(self.contentBox_2)
        self.contentBottom_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBottom_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottom_2.setObjectName("contentBottom_2")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.contentBottom_2)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.home_content = QtWidgets.QWidget(self.contentBottom_2)
        self.home_content.setMinimumSize(QtCore.QSize(500, 0))
        self.home_content.setStyleSheet("")
        self.home_content.setObjectName("home_content")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.home_content)
        self.horizontalLayout_13.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.books_frame = QtWidgets.QFrame(self.home_content)
        self.books_frame.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(221, 221, 221);;\n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"background: rgb(189, 147, 249);\n"
"color: black;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}\n"
"")
        self.books_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.books_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.books_frame.setObjectName("books_frame")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.books_frame)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.scrollArea = QtWidgets.QScrollArea(self.books_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 524, 555))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.product2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product2.sizePolicy().hasHeightForWidth())
        self.product2.setSizePolicy(sizePolicy)
        self.product2.setMinimumSize(QtCore.QSize(250, 0))
        self.product2.setStyleSheet("")
        self.product2.setObjectName("product2")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.product2)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.frame_12 = QtWidgets.QFrame(self.product2)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_12.setStyleSheet("QFrame {\n"
"border: none;\n"
"background: white;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_35.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.product2_image = QtWidgets.QLabel(self.frame_12)
        self.product2_image.setMaximumSize(QtCore.QSize(16777215, 250))
        self.product2_image.setStyleSheet("")
        self.product2_image.setText("")
        self.product2_image.setPixmap(QtGui.QPixmap(":/books/images/books/bree-anne-3AJoc9iJjo8-unsplash-small.jpg"))
        self.product2_image.setScaledContents(True)
        self.product2_image.setObjectName("product2_image")
        self.verticalLayout_35.addWidget(self.product2_image, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_34.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.product2)
        self.frame_13.setStyleSheet("QFrame {\n"
"border: none;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.product2_title = QtWidgets.QLabel(self.frame_13)
        self.product2_title.setStyleSheet("color: rgb(221, 221, 221);\n"
"font: 10pt \"Segoe UI\";\n"
"")
        self.product2_title.setAlignment(QtCore.Qt.AlignCenter)
        self.product2_title.setWordWrap(True)
        self.product2_title.setObjectName("product2_title")
        self.verticalLayout_36.addWidget(self.product2_title)
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.quantity_label = QtWidgets.QLabel(self.frame_14)
        self.quantity_label.setObjectName("quantity_label")
        self.horizontalLayout_16.addWidget(self.quantity_label)
        self.product2_price = QtWidgets.QLabel(self.frame_14)
        self.product2_price.setObjectName("product2_price")
        self.horizontalLayout_16.addWidget(self.product2_price)
        self.verticalLayout_36.addWidget(self.frame_14)
        self.product2_button = QtWidgets.QPushButton(self.frame_13)
        self.product2_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.product2_button.setObjectName("product2_button")
        self.verticalLayout_36.addWidget(self.product2_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_34.addWidget(self.frame_13)
        self.gridLayout.addWidget(self.product2, 0, 0, 1, 1)
        self.product2_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product2_4.sizePolicy().hasHeightForWidth())
        self.product2_4.setSizePolicy(sizePolicy)
        self.product2_4.setMinimumSize(QtCore.QSize(250, 0))
        self.product2_4.setStyleSheet("")
        self.product2_4.setObjectName("product2_4")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.product2_4)
        self.verticalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.frame_21 = QtWidgets.QFrame(self.product2_4)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_21.setStyleSheet("QFrame {\n"
"border: none;\n"
"background: white;\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_44.setContentsMargins(9, 9, -1, 9)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.product2_image_4 = QtWidgets.QLabel(self.frame_21)
        self.product2_image_4.setMaximumSize(QtCore.QSize(16777215, 250))
        self.product2_image_4.setStyleSheet("")
        self.product2_image_4.setText("")
        self.product2_image_4.setPixmap(QtGui.QPixmap(":/books/images/books/romeo_and_juliet-small.jpg"))
        self.product2_image_4.setScaledContents(True)
        self.product2_image_4.setObjectName("product2_image_4")
        self.verticalLayout_44.addWidget(self.product2_image_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_43.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.product2_4)
        self.frame_22.setStyleSheet("QFrame {\n"
"border: none;\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.product2_title_4 = QtWidgets.QLabel(self.frame_22)
        self.product2_title_4.setStyleSheet("color: rgb(221, 221, 221);\n"
"font: 10pt \"Segoe UI\";\n"
"")
        self.product2_title_4.setAlignment(QtCore.Qt.AlignCenter)
        self.product2_title_4.setWordWrap(True)
        self.product2_title_4.setObjectName("product2_title_4")
        self.verticalLayout_45.addWidget(self.product2_title_4)
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.product2_price_4 = QtWidgets.QLabel(self.frame_23)
        self.product2_price_4.setObjectName("product2_price_4")
        self.horizontalLayout_19.addWidget(self.product2_price_4)
        self.verticalLayout_45.addWidget(self.frame_23)
        self.product2_button_4 = QtWidgets.QPushButton(self.frame_22)
        self.product2_button_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.product2_button_4.setObjectName("product2_button_4")
        self.verticalLayout_45.addWidget(self.product2_button_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_43.addWidget(self.frame_22)
        self.gridLayout.addWidget(self.product2_4, 0, 1, 1, 1)
        self.product2_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product2_5.sizePolicy().hasHeightForWidth())
        self.product2_5.setSizePolicy(sizePolicy)
        self.product2_5.setMinimumSize(QtCore.QSize(250, 0))
        self.product2_5.setStyleSheet("")
        self.product2_5.setObjectName("product2_5")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.product2_5)
        self.verticalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.frame_24 = QtWidgets.QFrame(self.product2_5)
        self.frame_24.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_24.setStyleSheet("QFrame {\n"
"border: none;\n"
"background: white;\n"
"}")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_47.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.product2_image_5 = QtWidgets.QLabel(self.frame_24)
        self.product2_image_5.setMaximumSize(QtCore.QSize(16777215, 250))
        self.product2_image_5.setStyleSheet("")
        self.product2_image_5.setText("")
        self.product2_image_5.setPixmap(QtGui.QPixmap(":/books/images/books/bree-anne-3AJoc9iJjo8-unsplash-small.jpg"))
        self.product2_image_5.setScaledContents(True)
        self.product2_image_5.setObjectName("product2_image_5")
        self.verticalLayout_47.addWidget(self.product2_image_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_46.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.product2_5)
        self.frame_25.setStyleSheet("QFrame {\n"
"border: none;\n"
"}")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.product2_title_5 = QtWidgets.QLabel(self.frame_25)
        self.product2_title_5.setStyleSheet("color: rgb(221, 221, 221);\n"
"font: 10pt \"Segoe UI\";\n"
"")
        self.product2_title_5.setAlignment(QtCore.Qt.AlignCenter)
        self.product2_title_5.setWordWrap(True)
        self.product2_title_5.setObjectName("product2_title_5")
        self.verticalLayout_49.addWidget(self.product2_title_5)
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.product2_price_5 = QtWidgets.QLabel(self.frame_26)
        self.product2_price_5.setObjectName("product2_price_5")
        self.horizontalLayout_20.addWidget(self.product2_price_5)
        self.verticalLayout_49.addWidget(self.frame_26)
        self.product2_button_5 = QtWidgets.QPushButton(self.frame_25)
        self.product2_button_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.product2_button_5.setObjectName("product2_button_5")
        self.verticalLayout_49.addWidget(self.product2_button_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_46.addWidget(self.frame_25)
        self.gridLayout.addWidget(self.product2_5, 1, 1, 1, 1)
        self.product2_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product2_2.sizePolicy().hasHeightForWidth())
        self.product2_2.setSizePolicy(sizePolicy)
        self.product2_2.setMinimumSize(QtCore.QSize(250, 0))
        self.product2_2.setStyleSheet("")
        self.product2_2.setObjectName("product2_2")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.product2_2)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.gridLayout.addWidget(self.product2_2, 2, 0, 1, 1)
        self.product2_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product2_3.sizePolicy().hasHeightForWidth())
        self.product2_3.setSizePolicy(sizePolicy)
        self.product2_3.setMinimumSize(QtCore.QSize(250, 0))
        self.product2_3.setStyleSheet("")
        self.product2_3.setObjectName("product2_3")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.product2_3)
        self.verticalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.gridLayout.addWidget(self.product2_3, 2, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_33.addWidget(self.scrollArea)
        self.horizontalLayout_13.addWidget(self.books_frame)
        self.cart_frame = QtWidgets.QFrame(self.home_content)
        self.cart_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.cart_frame.setMaximumSize(QtCore.QSize(475, 16777215))
        self.cart_frame.setStyleSheet("QFrame {\n"
"border: 2px solid rgb(221, 221, 221);\n"
"}\n"
"\n"
"QLabel {\n"
"border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"background: transparent;\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(221, 221, 221);;\n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"background: rgb(189, 147, 249);\n"
"color: black;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"QPushButton:pressed {    \n"
"background-color: transparent;\n"
"}\n"
"")
        self.cart_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cart_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cart_frame.setObjectName("cart_frame")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.cart_frame)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.cart = QtWidgets.QFrame(self.cart_frame)
        self.cart.setStyleSheet("QFrame {\n"
"border: none\n"
"}\n"
"")
        self.cart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cart.setObjectName("cart")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.cart)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.cart_tableWidget = QtWidgets.QTableWidget(self.cart)
        self.cart_tableWidget.setStyleSheet("QTableWidget {\n"
"border: 1px solid white;\n"
"color: black;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"border: 1px solid white;\n"
"}\n"
"")
        self.cart_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.cart_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.cart_tableWidget.setObjectName("cart_tableWidget")
        self.cart_tableWidget.setColumnCount(4)
        self.cart_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cart_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_32.addWidget(self.cart_tableWidget)
        self.remove_from_cart_button = QtWidgets.QPushButton(self.cart)
        self.remove_from_cart_button.setObjectName("remove_from_cart_button")
        self.verticalLayout_32.addWidget(self.remove_from_cart_button)
        self.place_order_button = QtWidgets.QPushButton(self.cart)
        self.place_order_button.setObjectName("place_order_button")
        self.verticalLayout_32.addWidget(self.place_order_button)
        self.verticalLayout_31.addWidget(self.cart)
        self.status_frame = QtWidgets.QFrame(self.cart_frame)
        self.status_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.status_frame.setStyleSheet("border: none;")
        self.status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_frame.setObjectName("status_frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.status_frame)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.status_label = QtWidgets.QLabel(self.status_frame)
        self.status_label.setStyleSheet("color: rgb(189, 147, 249);")
        self.status_label.setText("")
        self.status_label.setWordWrap(True)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout_14.addWidget(self.status_label)
        self.verticalLayout_31.addWidget(self.status_frame)
        self.booksLogoutBtn = QtWidgets.QPushButton(self.cart_frame)
        self.booksLogoutBtn.setObjectName("booksLogoutBtn")
        self.verticalLayout_31.addWidget(self.booksLogoutBtn)
        self.verticalLayout_31.setStretch(0, 3)
        self.horizontalLayout_13.addWidget(self.cart_frame)
        self.horizontalLayout_13.setStretch(0, 5)
        self.horizontalLayout_13.setStretch(1, 2)
        self.verticalLayout_30.addWidget(self.home_content)
        self.verticalLayout_10.addWidget(self.contentBottom_2)
        self.verticalLayout_48.addWidget(self.contentBox_2)
        self.stackedWidget.addWidget(self.homePage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.styleWidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.adminStackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bookshop"))
        self.label_4.setText(_translate("MainWindow", "LOGIN PAGE"))
        self.welcome_message.setText(_translate("MainWindow", "Welcome to our Application!"))
        self.labelUsername.setText(_translate("MainWindow", "Username"))
        self.labelPassword.setText(_translate("MainWindow", "Password"))
        self.loginBtn.setText(_translate("MainWindow", "LOGIN"))
        self.signup_link_message.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.signupCommandBtn.setText(_translate("MainWindow", "Signup"))
        self.label_5.setText(_translate("MainWindow", "SIGNUP PAGE"))
        self.welcome_message_2.setText(_translate("MainWindow", "Welcome to our Application!"))
        self.labelUsername_2.setText(_translate("MainWindow", "Username"))
        self.labelPassword_2.setText(_translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "Confirm Password"))
        self.signupBtn.setText(_translate("MainWindow", "SIGNUP"))
        self.login_link_message.setText(_translate("MainWindow", "Already have an account?"))
        self.loginCommandBtn.setText(_translate("MainWindow", "Login"))
        self.btn_users.setText(_translate("MainWindow", "Customers"))
        self.btn_books.setText(_translate("MainWindow", "Products"))
        self.btn_orders.setText(_translate("MainWindow", "Orders"))
        self.btn_orderItems.setText(_translate("MainWindow", "PushButton"))
        self.customer_label.setText(_translate("MainWindow", "USERS"))
        item = self.userTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.userTableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.userTableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.userTableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.userTableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.userTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.userTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.userTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.userTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Is Admin"))
        self.user_add_button.setText(_translate("MainWindow", "Add"))
        self.user_update_button.setText(_translate("MainWindow", "Update"))
        self.user_delete_button.setText(_translate("MainWindow", "Delete"))
        self.product_label.setText(_translate("MainWindow", "BOOKS"))
        item = self.bookTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.bookTableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.bookTableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.bookTableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.bookTableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.bookTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.bookTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.bookTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Author"))
        item = self.bookTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.bookTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Price"))
        item = self.bookTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Image"))
        self.book_add_button.setText(_translate("MainWindow", "Add"))
        self.book_update_button.setText(_translate("MainWindow", "Update"))
        self.book_delete_button.setText(_translate("MainWindow", "Delete"))
        self.order_label.setText(_translate("MainWindow", "ORDERS"))
        item = self.orderTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.orderTableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.orderTableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.orderTableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.orderTableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.orderTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.orderTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer Name"))
        item = self.orderTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total Price"))
        item = self.orderTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date Added"))
        self.order_add_button.setText(_translate("MainWindow", "Add"))
        self.order_update_button.setText(_translate("MainWindow", "Update"))
        self.order_delete_button.setText(_translate("MainWindow", "Delete"))
        self.order_item_label.setText(_translate("MainWindow", "ORDER ITEMS"))
        item = self.orderItemTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.orderItemTableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.orderItemTableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.orderItemTableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.orderItemTableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.orderItemTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item ID"))
        item = self.orderItemTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Order ID"))
        item = self.orderItemTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book ID"))
        item = self.orderItemTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.orderItemTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Price"))
        self.order_item_add_button.setText(_translate("MainWindow", "Add"))
        self.order_item_update_button.setText(_translate("MainWindow", "Update"))
        self.order_item_delete_button.setText(_translate("MainWindow", "Delete"))
        self.product2_title.setText(_translate("MainWindow", "Mere Christianity by C.S LEWIS"))
        self.quantity_label.setText(_translate("MainWindow", "Quantity:"))
        self.product2_price.setText(_translate("MainWindow", "<html><head/><body><p>Price:<span style=\" font-weight:600;\"> $10</span></p></body></html>"))
        self.product2_button.setText(_translate("MainWindow", "Add to Cart"))
        self.product2_title_4.setText(_translate("MainWindow", "Mere Christianity by C.S LEWIS"))
        self.product2_price_4.setText(_translate("MainWindow", "<html><head/><body><p>Price:<span style=\" font-weight:600;\"> $10</span></p></body></html>"))
        self.product2_button_4.setText(_translate("MainWindow", "Add to Cart"))
        self.product2_title_5.setText(_translate("MainWindow", "Mere Christianity by C.S LEWIS"))
        self.product2_price_5.setText(_translate("MainWindow", "<html><head/><body><p>Price:<span style=\" font-weight:600;\"> $10</span></p></body></html>"))
        self.product2_button_5.setText(_translate("MainWindow", "Add to Cart"))
        item = self.cart_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", " Book"))
        item = self.cart_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Author"))
        item = self.cart_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total Price"))
        item = self.cart_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantity"))
        self.remove_from_cart_button.setText(_translate("MainWindow", "Remove from Cart"))
        self.place_order_button.setText(_translate("MainWindow", "Place Order"))
        self.booksLogoutBtn.setText(_translate("MainWindow", "Log Out"))
from . import resources_rc
